spring:
  application:
    name: CriandoProjetoSpringBoot
  datasource:
    username: sa
    url: jdbc:h2:mem:products
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081